spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    username: sa
    url: 'jdbc:h2:mem:db;MODE=MYSQL';
    password: ''
  h2:
    console:
      enabled: 'true'

  thymeleaf:
    cache: 'false'
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update

jwt:
  secret:
    key: '7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA='

cloud:
  aws:
    credentials:
      access-key:
      secret-key: 
    region:
      static: 'ap-northeast-2'
    s3:
      bucket: 'hanghae99pin'
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error